#!/usr/bin/env bash
#
# Regenerates web/src/data/cli-reference.generated.txt from the real
# `shep` binary's own --help output — every verb, exactly as clap renders
# it. Same precedent as docs/whistle/tools.md (generated by a `#[ignore]`d
# test from the live MCP routers): the CLI reference page must not drift
# from the code, so nothing in this file is hand-typed.
#
# Usage, from the repo root:
#   cargo build --release
#   ./web/scripts/generate-cli-reference.sh
#
# Re-run it whenever a verb, alias, or flag changes in crates/shep-cli/src/cli.rs
# — `web/src/data/cliReference.ts` parses this file at Astro build time, so a
# stale copy just means the reference page falls behind, not a build failure.
# `git diff` after running is the check.

set -euo pipefail

# Run the binary with a clean environment. clap renders an `[env: VAR=]`
# line showing the variable's CURRENT value, so a generator run in a shell
# that happens to have SHEP_HOME set bakes that path into the published
# reference -- caught 2026-08-20, one regeneration away from committing
# `[env: SHEP_HOME=/tmp/docdemo/home]` to the docs site.
shep() { env -u SHEP_HOME -u SHEP_STYLE -u NO_COLOR "$BIN" "$@"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# `shep` on unix, `shep.exe` on Windows. Checked in that order rather than
# branching on `$OSTYPE`: this script runs under Git Bash and WSL as well as
# a native shell, and which of those is "Windows" is not a question worth
# asking when the artifact itself answers it.
BIN="$REPO_ROOT/target/release/shep"
if [[ ! -x "$BIN" && -x "$BIN.exe" ]]; then
  BIN="$BIN.exe"
fi
OUT="$SCRIPT_DIR/../src/data/cli-reference.generated.txt"

if [[ ! -x "$BIN" ]]; then
  echo "error: $BIN not found or not executable — run 'cargo build --release' first" >&2
  exit 1
fi

# Every verb `shep --help` lists, in the order it lists them (declaration
# order in the Commands enum). `resurrect` is a deliberately hidden alias
# of `muster` (clap `alias`, not `visible_alias`) and stays out of this
# list on purpose — it must not appear in generated docs either.
#
# This list is hand-kept, and for a long time nothing checked it: `style`
# and `welcome` shipped and were simply absent from the published
# reference, because regenerating the file refreshes what is listed here
# and can say nothing about what is not. `verbs_the_reference_generator_
# misses` in `cli.rs` now compares it against the binary's own visible
# subcommands, so a new verb fails a test rather than going quietly
# undocumented. `help` is clap's own and is the one deliberate omission.
VERBS=(
  start serve stop restart reload delete stock flock dogs enable disable
  adopt rehome describe trigger signal whisper fold bleats lookout whistle
  reopen flush barks set get unset ping kill save muster runtime dev
  import startup unstartup completions init style welcome
)

{
  echo "@@VERSION@@"
  shep --version
  echo "@@TOPLEVEL@@"
  shep --help
  for v in "${VERBS[@]}"; do
    echo "@@VERB:$v@@"
    shep "$v" --help
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines, ${#VERBS[@]} verbs)"
