#!/usr/bin/env bash
#
# Regenerates web/src/data/cli-reference.generated.txt from the real
# `shep` binary's own --help output — every verb, exactly as clap renders
# it. Same precedent as docs/whistle/tools.md (generated by a `#[ignore]`d
# test from the live MCP routers): the CLI reference page must not drift
# from the code, so nothing in this file is hand-typed.
#
# Usage, from the repo root:
#   cargo build --release
#   ./web/scripts/generate-cli-reference.sh
#
# Re-run it whenever a verb, alias, or flag changes in crates/shep-cli/src/cli.rs
# — `web/src/data/cliReference.ts` parses this file at Astro build time, so a
# stale copy just means the reference page falls behind, not a build failure.
# `git diff` after running is the check.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BIN="$REPO_ROOT/target/release/shep"
OUT="$SCRIPT_DIR/../src/data/cli-reference.generated.txt"

if [[ ! -x "$BIN" ]]; then
  echo "error: $BIN not found or not executable — run 'cargo build --release' first" >&2
  exit 1
fi

# Every verb `shep --help` lists, in the order it lists them (declaration
# order in the Commands enum). `resurrect` is a deliberately hidden alias
# of `muster` (clap `alias`, not `visible_alias`) and stays out of this
# list on purpose — it must not appear in generated docs either.
VERBS=(
  start serve stop restart reload delete stock flock dogs enable disable
  adopt rehome describe trigger signal whisper fold bleats lookout whistle
  reopen flush barks set get unset ping kill save muster runtime dev
  import startup unstartup completions
)

{
  echo "@@VERSION@@"
  "$BIN" --version
  echo "@@TOPLEVEL@@"
  "$BIN" --help
  for v in "${VERBS[@]}"; do
    echo "@@VERB:$v@@"
    "$BIN" "$v" --help
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines, ${#VERBS[@]} verbs)"
